// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatDatabase_ChitChatting_FullMethodName = "/ChatDatabase/ChitChatting"
)

// ChatDatabaseClient is the client API for ChatDatabase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatDatabaseClient interface {
	// Bidirectional streaming RPC (tunnel)
	ChitChatting(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChitChat, ChitChat], error)
}

type chatDatabaseClient struct {
	cc grpc.ClientConnInterface
}

func NewChatDatabaseClient(cc grpc.ClientConnInterface) ChatDatabaseClient {
	return &chatDatabaseClient{cc}
}

func (c *chatDatabaseClient) ChitChatting(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChitChat, ChitChat], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatDatabase_ServiceDesc.Streams[0], ChatDatabase_ChitChatting_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChitChat, ChitChat]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatDatabase_ChitChattingClient = grpc.BidiStreamingClient[ChitChat, ChitChat]

// ChatDatabaseServer is the server API for ChatDatabase service.
// All implementations must embed UnimplementedChatDatabaseServer
// for forward compatibility.
type ChatDatabaseServer interface {
	// Bidirectional streaming RPC (tunnel)
	ChitChatting(grpc.BidiStreamingServer[ChitChat, ChitChat]) error
	mustEmbedUnimplementedChatDatabaseServer()
}

// UnimplementedChatDatabaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatDatabaseServer struct{}

func (UnimplementedChatDatabaseServer) ChitChatting(grpc.BidiStreamingServer[ChitChat, ChitChat]) error {
	return status.Errorf(codes.Unimplemented, "method ChitChatting not implemented")
}
func (UnimplementedChatDatabaseServer) mustEmbedUnimplementedChatDatabaseServer() {}
func (UnimplementedChatDatabaseServer) testEmbeddedByValue()                      {}

// UnsafeChatDatabaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatDatabaseServer will
// result in compilation errors.
type UnsafeChatDatabaseServer interface {
	mustEmbedUnimplementedChatDatabaseServer()
}

func RegisterChatDatabaseServer(s grpc.ServiceRegistrar, srv ChatDatabaseServer) {
	// If the following call pancis, it indicates UnimplementedChatDatabaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatDatabase_ServiceDesc, srv)
}

func _ChatDatabase_ChitChatting_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatDatabaseServer).ChitChatting(&grpc.GenericServerStream[ChitChat, ChitChat]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatDatabase_ChitChattingServer = grpc.BidiStreamingServer[ChitChat, ChitChat]

// ChatDatabase_ServiceDesc is the grpc.ServiceDesc for ChatDatabase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatDatabase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChatDatabase",
	HandlerType: (*ChatDatabaseServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChitChatting",
			Handler:       _ChatDatabase_ChitChatting_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto.proto",
}
